name: Deploy API

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - 'packages/database/**'
      - '.github/workflows/api-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        npm install
        
    - name: Build Database Package
      run: |
        npm run build --workspace=@nathanpass/database
        
    - name: Build API
      run: |
        npm run build --workspace=apps/api
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/nathanpass
          git pull origin main
          npm install
          npm run build --workspace=@nathanpass/database
          npm run build --workspace=apps/api
          pm2 restart api 